# Generated by Django 4.2.13 on 2024-07-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='owner',
            field=models.CharField(default='', max_length=50),
        ),
    ]
