# Generated by Django 5.0.3 on 2024-04-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientApp', '0003_client_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
