# Generated by Django 5.0.3 on 2024-05-06 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientApp', '0004_alter_client_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='face_encodings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid client code. This value may contain only letters, numbers, and ./- characters.', regex='^[\\w.-]+$')]),
        ),
    ]
